version: '3'
services:
  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: ./app
    volumes:
      - "./app:/app"
    container_name: golang_app
    ports:
      - "8080:8081"
    tty: true
    depends_on:
      - db
  app2:
    build:
      context: ./app2
    volumes:
      - "./app2:/app2"
    container_name: golang_app2
    ports:
      - "8082:8081"
    tty: true
  